=== conan513/l2mobius-helios/game/data/xsd/npcs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="dropListItem">
		<xs:attribute name="id" type="xs:positiveInteger" use="required" />
		<xs:attribute name="min" type="xs:nonNegativeInteger" />
		<xs:attribute name="max" type="xs:positiveInteger" />
		<xs:attribute name="chance" type="xs:decimal" />
	</xs:complexType>
	<xs:complexType name="dropList">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="item" type="dropListItem" />
		</xs:choice>
	</xs:complexType>
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="npc" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:all>
							<xs:element name="parameters" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:choice minOccurs="1" maxOccurs="unbounded">
										<xs:element name="param">
											<xs:complexType>
												<xs:attribute name="name" type="xs:token" use="required" />
												<xs:attribute name="value" type="xs:string" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="skill">
											<xs:complexType>
												<xs:attribute name="name" type="xs:token" use="required" />
												<xs:attribute name="id" type="xs:positiveInteger" use="required" />
												<xs:attribute name="level" type="xs:positiveInteger" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="minions">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="npc" minOccurs="1" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="id" type="xs:positiveInteger" use="required" />
															<xs:attribute name="count" type="xs:positiveInteger" use="required" />
															<xs:attribute name="respawnTime" type="xs:nonNegativeInteger" use="required" />
															<xs:attribute name="weightPoint" type="xs:integer" use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="name" type="xs:token" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:choice>
								</xs:complexType>
							</xs:element>
							<xs:element name="race" type="xs:token" minOccurs="0" maxOccurs="1" />
							<xs:element name="sex" type="xs:token" minOccurs="0" maxOccurs="1" />
							<xs:element name="equipment" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="chest" type="xs:nonNegativeInteger" />
									<xs:attribute name="rhand" type="xs:nonNegativeInteger" />
									<xs:attribute name="lhand" type="xs:nonNegativeInteger" />
									<xs:attribute name="weaponEnchant" type="xs:nonNegativeInteger" />
								</xs:complexType>
							</xs:element>
							<xs:element name="acquire" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="exp" type="xs:decimal" />
									<xs:attribute name="sp" type="xs:decimal" />
									<xs:attribute name="raidPoints" type="xs:decimal" />
								</xs:complexType>
							</xs:element>
							<xs:element name="mpReward" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="value" type="xs:positiveInteger" />
									<xs:attribute name="type">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="DIFF" />
												<xs:enumeration value="PER" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="ticks" type="xs:positiveInteger" />
									<xs:attribute name="affects">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="SOLO" />
												<xs:enumeration value="PARTY" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="stats" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:all>
										<xs:element name="vitals" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="hp" type="xs:decimal" />
												<xs:attribute name="hpRegen" type="xs:decimal" />
												<xs:attribute name="mp" type="xs:decimal" />
												<xs:attribute name="mpRegen" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
										<xs:element name="attack" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="physical" type="xs:decimal" />
												<xs:attribute name="magical" type="xs:decimal" />
												<xs:attribute name="random" type="xs:nonNegativeInteger" />
												<xs:attribute name="critical" type="xs:decimal" />
												<xs:attribute name="accuracy" type="xs:float" />
												<xs:attribute name="attackSpeed" type="xs:float" />
												<xs:attribute name="reuseDelay" type="xs:nonNegativeInteger" />
												<xs:attribute name="type" type="xs:token" />
												<xs:attribute name="range" type="xs:nonNegativeInteger" />
												<xs:attribute name="distance" type="xs:nonNegativeInteger" />
												<xs:attribute name="width" type="xs:nonNegativeInteger" />
											</xs:complexType>
										</xs:element>
										<xs:element name="defence" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="physical" type="xs:decimal" />
												<xs:attribute name="magical" type="xs:decimal" />
												<xs:attribute name="evasion" type="xs:integer" />
												<xs:attribute name="shield" type="xs:nonNegativeInteger" />
												<xs:attribute name="shieldRate" type="xs:nonNegativeInteger" />
											</xs:complexType>
										</xs:element>
										<xs:element name="abnormalResist" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="physical" type="xs:decimal" />
												<xs:attribute name="magical" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
										<xs:element name="attribute" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:all>
													<xs:element name="attack" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:attribute name="type" type="xs:token" />
															<xs:attribute name="value" type="xs:nonNegativeInteger" />
														</xs:complexType>
													</xs:element>
													<xs:element name="defence" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:attribute name="fire" type="xs:integer" />
															<xs:attribute name="water" type="xs:integer" />
															<xs:attribute name="wind" type="xs:integer" />
															<xs:attribute name="earth" type="xs:integer" />
															<xs:attribute name="holy" type="xs:integer" />
															<xs:attribute name="dark" type="xs:integer" />
															<xs:attribute name="default" type="xs:integer" />
														</xs:complexType>
													</xs:element>
												</xs:all>
											</xs:complexType>
										</xs:element>
										<xs:element name="speed" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:all>
													<xs:element name="walk" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:attribute name="ground" type="xs:decimal" />
															<xs:attribute name="swim" type="xs:decimal" />
															<xs:attribute name="fly" type="xs:decimal" />
														</xs:complexType>
													</xs:element>
													<xs:element name="run" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:attribute name="ground" type="xs:decimal" />
															<xs:attribute name="swim" type="xs:decimal" />
															<xs:attribute name="fly" type="xs:decimal" />
														</xs:complexType>
													</xs:element>
												</xs:all>
											</xs:complexType>
										</xs:element>
										<xs:element name="hitTime" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="1" />
									</xs:all>
									<xs:attribute name="str" type="xs:nonNegativeInteger" />
									<xs:attribute name="int" type="xs:nonNegativeInteger" />
									<xs:attribute name="dex" type="xs:nonNegativeInteger" />
									<xs:attribute name="wit" type="xs:nonNegativeInteger" />
									<xs:attribute name="con" type="xs:nonNegativeInteger" />
									<xs:attribute name="men" type="xs:nonNegativeInteger" />
								</xs:complexType>
							</xs:element>
							<xs:element name="status" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="unique" type="xs:boolean" />
									<xs:attribute name="attackable" type="xs:boolean" />
									<xs:attribute name="talkable" type="xs:boolean" />
									<xs:attribute name="targetable" type="xs:boolean" />
									<xs:attribute name="undying" type="xs:boolean" />
									<xs:attribute name="showName" type="xs:boolean" />
									<xs:attribute name="randomWalk" type="xs:boolean" />
									<xs:attribute name="randomAnimation" type="xs:boolean" />
									<xs:attribute name="flying" type="xs:boolean" />
									<xs:attribute name="canMove" type="xs:boolean" />
									<xs:attribute name="noSleepMode" type="xs:boolean" />
									<xs:attribute name="passableDoor" type="xs:boolean" />
									<xs:attribute name="hasSummoner" type="xs:boolean" />
									<xs:attribute name="canBeSown" type="xs:boolean" />
									<xs:attribute name="isDeathPenalty" type="xs:boolean" />
									<xs:attribute name="fakePlayer" type="xs:boolean" />
									<xs:attribute name="fakePlayerTalkable" type="xs:boolean" />
								</xs:complexType>
							</xs:element>
							<xs:element name="skillList" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="skill" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:nonNegativeInteger" use="required" />
												<xs:attribute name="level" type="xs:nonNegativeInteger" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="shots" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="soul" type="xs:nonNegativeInteger" />
									<xs:attribute name="spirit" type="xs:nonNegativeInteger" />
									<xs:attribute name="shotChance" type="xs:nonNegativeInteger" />
									<xs:attribute name="spiritChance" type="xs:nonNegativeInteger" />
								</xs:complexType>
							</xs:element>
							<xs:element name="corpseTime" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="1" />
							<xs:element name="exCrtEffect" type="xs:boolean" minOccurs="0" maxOccurs="1" />
							<xs:element name="sNpcPropHpRate" type="xs:decimal" minOccurs="0" maxOccurs="1" />
							<xs:element name="ai" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:all>
										<xs:element name="skill" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="minChance" type="xs:nonNegativeInteger" />
												<xs:attribute name="maxChance" type="xs:nonNegativeInteger" />
												<xs:attribute name="primaryId" type="xs:nonNegativeInteger" />
												<xs:attribute name="shortRangeId" type="xs:nonNegativeInteger" />
												<xs:attribute name="shortRangeChance" type="xs:nonNegativeInteger" />
												<xs:attribute name="longRangeId" type="xs:nonNegativeInteger" />
												<xs:attribute name="longRangeChance" type="xs:nonNegativeInteger" />
											</xs:complexType>
										</xs:element>
										<xs:element name="clanList" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:choice minOccurs="1" maxOccurs="unbounded">
													<xs:element name="clan" type="xs:token" />
													<xs:element name="ignoreNpcId" type="xs:nonNegativeInteger" />
												</xs:choice>
											</xs:complexType>
										</xs:element>
									</xs:all>
									<xs:attribute name="type" type="xs:token" />
									<xs:attribute name="aggroRange" type="xs:nonNegativeInteger" />
									<xs:attribute name="clanHelpRange" type="xs:nonNegativeInteger" />
									<xs:attribute name="dodge" type="xs:nonNegativeInteger" />
									<xs:attribute name="isChaos" type="xs:boolean" />
									<xs:attribute name="isAggressive" type="xs:boolean" />
								</xs:complexType>
							</xs:element>
							<xs:element name="dropLists" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:all>
										<xs:element name="drop" type="dropList" minOccurs="0" maxOccurs="1" />
										<xs:element name="spoil" type="dropList" minOccurs="0" maxOccurs="1" />
										<xs:element name="lucky" type="dropList" minOccurs="0" maxOccurs="1" />
									</xs:all>
								</xs:complexType>
							</xs:element>
							<xs:element name="collision" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:all>
										<xs:element name="radius" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="normal" type="xs:decimal" />
												<xs:attribute name="grown" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
										<xs:element name="height" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="normal" type="xs:decimal" />
												<xs:attribute name="grown" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
									</xs:all>
								</xs:complexType>
							</xs:element>
							<xs:element name="extendDrop" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:byte" name="id" maxOccurs="unbounded" minOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:all>
						<xs:attribute name="id" type="xs:positiveInteger" use="required" />
						<xs:attribute name="displayId" type="xs:positiveInteger" />
						<xs:attribute name="level" type="xs:byte" />
						<xs:attribute name="type" type="xs:token" />
						<xs:attribute name="name" type="xs:string" />
						<xs:attribute name="usingServerSideName" type="xs:boolean" />
						<xs:attribute name="title" type="xs:string" />
						<xs:attribute name="usingServerSideTitle" type="xs:boolean" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== conan513/l2mobius-helios/game/data/stats/npcs/33800-33899.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/npcs.xsd">
	<npc id="33800" level="95" type="L2Monster" name="Life Plunderer">
		<!-- AUTO GENERATED NPC TODO: FIX IT -->
		<race>FAIRY</race>
		<sex>MALE</sex>
		<mpReward value="20" type="PER" ticks="10" affects="PARTY" />
		<stats str="88" int="79" dex="55" wit="78" con="82" men="78">
			<vitals hp="17244" hpRegen="1" mp="1" mpRegen="1" />
			<speed>
				<walk ground="80" />
				<run ground="1" />
			</speed>
			<attack physical="1" magical="1" critical="4" attackSpeed="253" range="40" type="SWORD" distance="80" width="120" random="10" accuracy="5" />
			<defence physical="5000" magical="5000" />
			<attribute>
				<defence fire="20" water="20" wind="20" earth="20" holy="20" dark="20" />
			</attribute>
			<abnormalResist physical="0" magical="0" />
		</stats>
		<status attackable="false" canMove="false" />
		<skillList>
			<skill id="4390" level="1" /> <!-- NPC Abnormal Immunity -->
			<skill id="4415" level="3" /> <!-- One-handed Sword -->
			<skill id="4045" level="1" /> <!-- Resist Full Magic Attack -->
			<skill id="4416" level="13" /> <!-- Fairies -->
		</skillList>
		<collision>
			<radius normal="45" />
			<height normal="78" />
		</collision>
	</npc>
	<npc id="33801" level="99" type="L2Npc" name="Turetta" title="Appearance Modification Guide">
		<!-- AUTO GENERATED NPC TODO: FIX IT -->
		<race>HUMAN</race>
		<sex>FEMALE</sex>
		<mpReward value="20" type="PER" ticks="10" affects="PARTY" />
		<stats str="88" int="79" dex="55" wit="78" con="82" men="78">
			<vitals hp="8446" hpRegen="8.5" mp="2355" mpRegen="3" />
			<speed>
				<walk ground="64" />
				<run ground="1" />
			</speed>
			<attack physical="1949.95411856464" magical="1331.56588332443" critical="4" attackSpeed="253" range="40" type="SWORD" distance="80" width="120" random="10" accuracy="5" />
			<defence physical="405.66735" magical="296.84976" />
			<attribute>
				<defence fire="20" water="20" wind="20" earth="20" holy="20" dark="20" />
			</attribute>
			<abnormalResist physical="0" magical="0" />
		</stats>
		<status attackable="false" />
		<skillList>
			<skill id="4416" level="14" /> <!-- Humans -->
			<skill id="4390" level="1" /> <!-- NPC Abnormal Immunity -->
			<skill id="4415" level="3" /> <!-- One-handed Sword -->
			<skill id="4045" level="1" /> <!-- Resist Full Magic Attack -->
		</skillList>
		<collision>
			<radius normal="13" />
			<height normal="22.5" />
		</collision>
	</npc>
	<npc id="33802" level="99" type="L2Npc" name="Memorable Raid Soul">
		<!-- AUTO GENERATED NPC TODO: FIX IT -->
		<race>UNDEAD</race>
		<sex>MALE</sex>
		<mpReward value="20" type="PER" ticks="10" affects="PARTY" />
		<stats str="88" int="79" dex="55" wit="78" con="82" men="78">
			<vitals hp="8446" hpRegen="8.5" mp="2355" mpRegen="3" />
			<speed>
				<walk ground="50" />
				<run ground="1" />
			</speed>
			<attack physical="1949.95411856464" magical="1331.56588332443" critical="4" attackSpeed="253" range="40" type="SWORD" distance="80" width="120" random="10" accuracy="5" />
			<defence physical="405.66735" magical="296.84976" />
			<attribute>
				<defence fire="20" water="20" wind="20" earth="20" holy="20" dark="20" />
			</attribute>
			<abnormalResist physical="0" magical="0" />
		</stats>
		<status attackable="false" />
		<skillList>
			<skill id="4390" level="1" /> <!-- NPC Abnormal Immunity -->
			<skill id="4416" level="1" /> <!-- Undead -->
			<skill id="4415" level="3" /> <!-- One-handed Sword -->
			<skill id="4045" level="1" /> <!-- Resist Full Magic Attack -->
		</skillList>
		<collision>
			<radius normal="8" />
			<height normal="22.5" />
		</collision>
	</npc>
	<npc id="33803" level="99" type="L2Npc" name="Razen" title="Priestess of Light">
		<!-- AUTO GENERATED NPC TODO: FIX IT -->
		<race>HUMAN</race>
		<sex>FEMALE</sex>
		<mpReward value="20" type="PER" ticks="10" affects="PARTY" />
		<stats str="88" int="79" dex="55" wit="78" con="82" men="78">
			<vitals hp="8446" hpRegen="8.5" mp="2355" mpRegen="3" />
			<speed>
				<walk ground="50" />
				<run ground="1" />
			</speed>
			<attack physical="1949.95411856464" magical="1331.56588332443" critical="4" attackSpeed="253" range="40" type="SWORD" distance="80" width="120" random="10" accuracy="5" />
			<defence physical="405.66735" magical="296.84976" />
			<attribute>
				<defence fire="20" water="20" wind="20" earth="20" holy="20" dark="20" />
			</attribute>
			<abnormalResist physical="0" magical="0" />
		</stats>
		<status attackable="false" />
		<skillList>
			<skill id="4416" level="14" /> <!-- Humans -->
			<skill id="4390" level="1" /> <!-- NPC Abnormal Immunity -->
			<skill id="4415" level="3" /> <!-- One-handed Sword -->
			<skill id="4045" level="1" /> <!-- Resist Full Magic Attack -->
		</skillList>
		<collision>
			<radius normal="8" />
			<height normal="22.5" />
		</collision>
	</npc>
	<npc id="33804" level="99" type="L2Npc" name="Charlotte" title="Tobald's Disciple">
		<!-- AUTO GENERATED NPC TODO: FIX IT -->
		<race>HUMAN</race>
		<sex>FEMALE</sex>
		<mpReward value="20" type="PER" ticks="10" affects="PARTY" />
		<stats str="88" int="79" dex="55" wit="78" con="82" men="78">
			<vitals hp="8446" hpRegen="8.5" mp="2355" mpRegen="3" />
			<speed>
				<walk ground="50" />
				<run ground="1" />
			</speed>
			<attack physical="1949.95411856464" magical="1331.56588332443" critical="4" attackSpeed="253" range="40" type="SWORD" distance="80" width="120" random="10" accuracy="5" />
			<defence physical="405.66735" magical="296.84976" />
			<attribute>
				<defence fire="20" water="20" wind="20" earth="20" holy="20" dark="20" />
			</attribute>
			<abnormalResist physical="0" magical="0" />
		</stats>
		<status attackable="false" />
		<skillList>
			<skill id="4416" level="14" /> <!-- Humans -->
			<skill id="4390" level="1" /> <!-- NPC Abnormal Immunity -->
			<skill id="4415" level="3" /> <!-- One-handed Sword -->
			<skill id="4045" level="1" /> <!-- Resist Full Magic Attack -->
		</skillList>
		<collision>
			<radius normal="12" />
			<height normal="17" />
		</collision>
	</npc>
	<npc id="33805" level="99" type="L2Npc" name="Tiffany" title="Dazzling">
		<!-- AUTO GENERATED NPC TODO: FIX IT -->
		<parameters>
			<param name="MoveAroundSocial" value="0" />
			<param name="MoveAroundSocial1" value="100" />
		</parameters>
		<race>ELF</race>
		<sex>FEMALE</sex>
		<equipment rhand="192" lhand="192" /> <!-- Crystal Staff / Crystal Staff -->
		<mpReward value="20" type="PER" ticks="10" affects="PARTY" />
		<stats str="88" int="79" dex="55" wit="78" con="82" men="78">
			<vitals hp="1" hpRegen="1" mp="1" mpRegen="1" />
			<speed>
				<walk ground="50" />
				<run ground="100" />
			</speed>
			<attack physical="1" magical="1" critical="4" attackSpeed="253" range="40" type="SWORD" distance="80" width="120" random="10" accuracy="5" />
			<defence physical="1" magical="1" />
			<attribute>
				<defence fire="20" water="20" wind="20" earth="20" holy="20" dark="20" />
			</attribute>
			<abnormalResist physical="0" magical="0" />
		</stats>
		<status attackable="false" />
		<skillList>
			<skill id="4390" level="1" /> <!-- NPC Abnormal Immunity -->
			<skill id="4415" level="3" /> <!-- One-handed Sword -->
			<skill id="4045" level="1" /> <!-- Resist Full Magic Attack -->
			<skill id="4416" level="15" /> <!-- Elves -->
		</skillList>
		<collision>
			<radius normal="7" />
			<height normal="21.2" />
		</collision>
	</npc>
	<npc id="33806" level="1" type="L2Npc" name="Dimensional Door">
		<!-- AUTO GENERATED NPC TODO: FIX IT -->
		<race>CONSTRUCT</race>
		<sex>ETC</sex>
		<mpReward value="20" type="PER" ticks="10" affects="PARTY" />
		<stats str="88" int="79" dex="55" wit="78" con="82" men="78">
			<vitals hp="39" hpRegen="2" mp="40" mpRegen="0.9" />
			<speed>
				<walk ground="60" />
				<run ground="60" />
			</speed>
			<attack physical="8.47458" magical="5.78704" critical="4" attackSpeed="253" range="40" type="FIST" distance="80" width="120" random="5" accuracy="5" />
			<defence physical="44.44444" magical="32.52252" />
			<attribute>
				<defence fire="20" water="20" wind="20" earth="20" holy="20" dark="20" />
			</attribute>
			<abnormalResist physical="0" magical="0" />
		</stats>
		<status attackable="false" />
		<skillList>
			<skill id="4416" level="2" /> <!-- Magic Creatures -->
			<skill id="4390" level="1" /> <!-- NPC Abnormal Immunity -->
			<skill id="4415" level="1" /> <!-- Bare Hands -->
			<skill id="4045" level="1" /> <!-- Resist Full Magic Attack -->
		</skillList>
		<collision>
			<radius normal="22" />
			<height normal="45" />
		</collision>
	</npc>
	<npc id="33807" level="99" type="L2Npc" name="Verdof" title="Gatekeeper of Dimensional Hell">
		<!-- AUTO GENERATED NPC TODO: FIX IT -->
		<race>DEMONIC</race>
		<sex>MALE</sex>
		<mpReward value="20" type="PER" ticks="10" affects="PARTY" />
		<stats str="88" int="79" dex="55" wit="78" con="82" men="78">
			<vitals hp="8446" hpRegen="8.5" mp="2355" mpRegen="3" />
			<speed>
				<walk ground="70" />
				<run ground="120" />
			</speed>
			<attack physical="1949.95411856464" magical="1331.56588332443" critical="4" attackSpeed="253" range="40" type="FIST" distance="80" width="120" random="5" accuracy="5" />
			<defence physical="405.66735" magical="296.84976" />
			<attribute>
				<defence fire="20" water="20" wind="20" earth="20" holy="20" dark="20" />
			</attribute>
			<abnormalResist physical="0" magical="0" />
		</stats>
		<status attackable="false" />
		<skillList>
			<skill id="4416" level="9" /> <!-- Demons -->
			<skill id="4415" level="1" /> <!-- Bare Hands -->
			<skill id="4045" level="1" /> <!-- Resist Full Magic Attack -->
		</skillList>
		<collision>
			<radius normal="17" />
			<height normal="55" />
		</collision>
	</npc>
	<npc id="33808" level="1" type="L2Npc" name="Destiny Treasure Chest">
		<!-- AUTO GENERATED NPC TODO: FIX IT -->
